name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "0 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Automated Update Via Github Actions:  Generated Github Statics"
          git push
